require('dotenv').config()
const cors = require('cors')
const express = require('express')
const app = express()
const port = process.env.PORT | 3000
const {errorHandler} = require('./middlewares/errorHandler')
const {register, login, fetchUsers} = require('./controllers/user')
const { addProduct, fetchProducts, editProduct, removeProduct, patchProduct } = require('./controllers/product')
const { fetchCategories, addCategory, editCategory, removeCategory } = require('./controllers/category')
const { fetchCustomers, addCustomer, editCustomer, removeCustomer } = require('./controllers/customer')
const getToken = require('./controllers/midtrans')
app.use(cors())
app.use(express.urlencoded({extended:false}))
app.use(express.json())

app.get('/', (req, res) => res.send('hello world'))
app.post('/register', register)
app.post('/login', login)
app.get('/users', fetchUsers)
app.get('/products', fetchProducts)
app.post('/products', addProduct)
app.put('/products/:id', editProduct)
app.patch('/products/:id', patchProduct)
app.delete('/products/:id', removeProduct)
app.get('/categories', fetchCategories)
app.post('/categories', addCategory)
app.put('/categories/:id', editCategory)
app.delete('/categories/:id', removeCategory)
app.get('/customers', fetchCustomers)
app.post('/customers', addCustomer)
app.put('/customers/:id', editCustomer)
app.delete('/customers/:id', removeCustomer)
app.post('/transactions', getToken)


app.use(errorHandler)

app.listen(port, () => console.log('App running on port', port))